cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name = 'cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name = 'cart_remove'),
]

shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'', include('shopmania.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopmania/urls.py
from django.conf.urls import url
from . import views

app_name = 'shopmania'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[\w-]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shopmania/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length = 120, db_index = True)
    slug = models.SlugField(max_length = 120, unique = True, db_index = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def  get_absolute_url(self):
        return reverse('shopmania:product_list_by_category', args= [self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name= 'products', on_delete=models.CASCADE)
    name = models.CharField(max_length = 100, db_index = True)
    company = models.CharField(max_length = 100)
    slug = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank = True)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    available = models.BooleanField(default = True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image_1 = models.ImageField(upload_to='%Y/%m/%d', blank=True)
    image_2 = models.ImageField(upload_to='%Y/%m/%d', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('shopmania:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices = PRODUCT_QUANTITY_CHOICES, coerce = int)
    update = forms.BooleanField(required = False, initial = False, widget = forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shopmania.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shopmania/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

 
def product_list(request, category_slug = None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category' : category,
        'categories' : categories,
        'products' : products
    }
    return render(request, 'shopmania/product/list.html', context)

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    print (product.image_1.url)
    return render(request, 'shopmania/product/detail.html', context)

cart/templates/cart/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>{% block title %} Your Shopping Cart {% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'css/cart/cart.css' %}" >
      <style>
      body{
  background-color: #F5F4EB;
}
.product-image {
  float: left;
  width: 20%;
}

.product-details {
  float: left;
  width: 37%;
}

.product-price {
  float: left;
  width: 12%;
}

.product-quantity {
  float: left;
  width: 10%;
}

.product-removal {
  float: left;
  width: 9%;
}

.product-line-price {
  float: left;
  width: 12%;
  text-align: right;
}

.group:before, .shopping-cart:before, .column-labels:before, .product:before, .totals-item:before,
.group:after,
.shopping-cart:after,
.column-labels:after,
.product:after,
.totals-item:after {
  content: '';
  display: table;
}

.group:after, .shopping-cart:after, .column-labels:after, .product:after, .totals-item:after {
  clear: both;
}

.group, .shopping-cart, .column-labels, .product, .totals-item {
  zoom: 1;
}

/* Apply clearfix in a few places */
/* Apply dollar signs */
.product .product-price:before, .product .product-line-price:before, .totals-value:before {
  content: 'Rs';
}

/* Body/Header stuff */
body {
  padding: 0px 30px 30px 20px;
  font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-weight: 100;
}

h1 {
  font-weight: 100;
}

label {
  color: #aaa;
}

.shopping-cart {
  margin-top: -45px;
}

/* Column headers */
.column-labels label {
  padding-bottom: 15px;
  margin-bottom: 15px;
  border-bottom: 1px solid #eee;
}
.column-labels .product-image, .column-labels .product-details, .column-labels .product-removal {
  text-indent: -9999px;
}

/* Product entries */
.product {
  margin-bottom: 20px;
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}
.product .product-image {
  text-align: center;
}
.product .product-image img {
  width: 100px;
    box-shadow: 10px 10px 5px #aaaaaa;
}
.product .product-details .product-title {
  margin-right: 20px;
  font-family: "HelveticaNeue-Medium", "Helvetica Neue Medium";
}
.product .product-details .product-description {
  margin: 5px 20px 5px 0;
  line-height: 1.4em;
}
.product .product-quantity input {
  width: 40px;
}
.product .remove-product {
  border: 0;
  padding: 4px 8px;
  background-color: #c66;
  color: #fff;
  font-family: "HelveticaNeue-Medium", "Helvetica Neue Medium";
  font-size: 12px;
  border-radius: 3px;
}
.product .remove-product:hover {
  background-color: #a44;
}

/* Totals section */
.totals .totals-item {
  float: right;
  clear: both;
  width: 100%;
  margin-bottom: 10px;
}
.totals .totals-item label {
  float: left;
  clear: both;
  width: 79%;
  text-align: right;
}
.totals .totals-item .totals-value {
  float: right;
  width: 21%;
  text-align: right;
}
.totals .totals-item-total {
  font-family: "HelveticaNeue-Medium", "Helvetica Neue Medium";
}

.checkout {
  float: right;
  display: inline-block;
  background-color: #f4511e;
  border: none;
  width: 200px;
  padding: 20px;
  background-color: #6b6;
  color: #FFFFFF;
  transition: all 0.5s;
  cursor: pointer;
  font-size: 20px;
  border-radius: 3px;
  margin: 3px;
  margin-top: 14px;
}


.checkout span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.checkout span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.checkout:hover span {
  padding-right: 25px;
}

.checkout:hover span:after {
  opacity: 1;
  right: 0;
}



/* Make adjustments for tablet */
@media screen and (max-width: 650px) {
  .shopping-cart {
    margin: 0;
    padding-top: 20px;
    border-top: 1px solid #eee;
  }

  .column-labels {
    display: none;
  }

  .product-image {
    float: right;
    width: auto;
  }
  .product-image img {
    margin: 0 0 10px 10px;
  }

  .product-details {
    float: none;
    margin-bottom: 10px;
    width: auto;
  }

  .product-price {
    clear: both;
    width: 70px;
  }

  .product-quantity {
    width: 100px;
  }
  .product-quantity input {
    margin-left: 20px;
  }

  .product-quantity:before {
    content: 'x';
  }

  .product-removal {
    width: auto;
  }

  .product-line-price {
    float: right;
    width: 70px;
  }
}
/* Make more adjustments for phone */
@media screen and (max-width: 350px) {
  .product-removal {
    float: right;
  }

  .product-line-price {
    float: right;
    clear: left;
    width: auto;
    margin-top: 10px;
  }

  .product .product-line-price:before {
    content: 'Item Total: Rs';
  }

  .totals .totals-item label {
    width: 60%;
  }
  .totals .totals-item .totals-value {
    width: 40%;
  }
}
</style>
</head>

<body>

  <h1 style="background-color:#222930;height:10vh;clip-path: polygon(0 0,100% 20%,90% 80%,0% 120%);color:#4EB1BA;text-shadow: 2px 2px black;font-family: lato;">SHOPPING CART</h1>
  <h2>Your Shopping Cart :
            {% with totail_items=cart|length %}
              {% if cart|length > 0 %}
                  <a href="{% url "cart:cart_detail" %}" style="color: blue">
                      {{ totail_items }} items , Rs. {{ cart.get_total_price }}
                  </a>
                  {% else %}
                  Your cart is empty.
              {% endif %}
          {% endwith %}

  </h2>
<div class="shopping-cart">
<br><br><br><br><br>
{% for item in cart %}
    {% with product=item.product  %}
  <div class="product">
    <div class="product-image">
      <a href="{{ product.get__absolute_url }}">
      <img src="{% if product.image_2 %} {{ product.image_2.url }} {% endif %}" alt="Product Image">
      </a>
    </div>
    <div class="product-details">
      <div class="product-title"> {{ product.name }}</div>
      <p class="product-description"> {{ product.description }} </p>
    </div>
    <div class="product-price">{{ product.price }}</div>
    <div class="product-quantity">
      <!-- <input type="number" value="1" min="1">  -->
      <form action="{% url "cart:cart_add" product.id %}" method="post">
          {% csrf_token %}
          {{ item.update_quantity_form.quantity }}
          {{ item.update_quantity_form.update }}
          <input type="submit" value="Update" style="width : 70px" >
      </form>
    </div>
    <div class="product-removal">
        <a href="{% url "cart:cart_remove" product.id %}">
      <button class="remove-product">
        Remove Item
      </button>
      </a>
    </div>
    <div class="product-line-price">{{ item.price }}</div>
  </div>

  <div class="totals">
    <div class="totals-item">
      <label>Subtotal</label>
      <div class="totals-value" id="cart-subtotal">{{ item.total_price}}</div>
    </div>
    {% endwith %}
{% endfor %}
    <!-- <div class="totals-item">
      <label>Tax (5%)</label>
      <div class="totals-value" id="cart-tax">100</div>
    </div>
    <div class="totals-item">
      <label>Shipping</label>
      <div class="totals-value" id="cart-shipping">500</div>
    </div>-->
    <div class="totals-item totals-item-total">
      <label>Grand Total</label>
      <div class="totals-value" id="cart-total">{{ cart.get_total_price }}</div>
    </div>
  </div>

      <a href="{% url "shopmania:product_list" %}" >
        <button class="checkout" ><span>Continue Shopping</span></button></a>
     <a href="" > <button class="checkout"><span>Checkout</span></button></a>
</div>

</div>

</body>
</html>

cart/templates/cart/detail_old.html
{% extends 'shopmania/base.html' %}
{% load static %}
{% block title %}
Your Shopping cart
{% endblock %}

{% block content %}

        <h2>Your Shopping Cart
                  {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}

        </h2>
            <table>
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image_2 %} {{ product.image_2.url }} {% endif %}" alt="Product Image" style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" >
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td> {{ item.price }}</td>
                            <td> {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td ></td>
                    <td ><b> {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p >
            <a href="{% url "shopmania:product_list" %}" >Continue Shopping</a>
            <a href="" >Checkout</a>
        </p>
{% endblock %}

shopmania/templates/shopmania/product/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>{{ product.name }}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

    <link rel="stylesheet" href="{% static 'css/product/detail.css' %}">
      <style>
      * {
  line-height: 1.5;

}

body {
  max-width: 1200px;
  margin: 0 auto;scroll-behavior: smooth;


}

section {
  margin-top: 2em;
}

.container {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  flex-direction: row;
  max-width: 1280px;
  padding-left: 15px;
  padding-right: 15px;
  margin-left: auto;
  margin-right: auto;
}

.col-6 {
  flex: 0 0 100%;
  margin: 5px 0;
}

@media (min-width: 1000px) {
  .col-6 {
    flex: 0 0 48.9%;
    margin: 5px auto;
  }
}
img {
  width: 100%;
}

.title {
  font-size: 2.5em;
  margin-bottom: 0;
}

.description {
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.btn-primary {
  align-self: left;
  background: black;
  color: white;
  border: none;
  padding: .8em 3em;
}







a{
  color:white;
}


div.table-title {
   display: block;
  margin: auto;
  max-width: 600px;
  padding:5px;
  width: 100%;
}

.table-title h3 {
   color: black;
   font-size: 30px;
   font-weight: 400;
   font-style:normal;
   font-family: "Roboto", helvetica, arial, sans-serif;
   text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
   text-transform:uppercase;
}


/*** Table Styles **/

.table-fill {
  background: white;
  border-radius:3px;
  border-collapse: collapse;
  height: 320px;
  margin: auto;
  max-width: 600px;
  padding:5px;
  width: 100%;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
  animation: float 5s infinite;
}

th {
  color:#D5DDE5;;
  background:#1b1e24;
  border-bottom:4px solid #9ea7af;
  border-right: 1px solid #343a45;
  font-size:23px;
  font-weight: 100;
  padding:24px;
  text-align:left;
  text-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
  vertical-align:middle;
}

th:first-child {
  border-top-left-radius:3px;
}

th:last-child {
  border-top-right-radius:3px;
  border-right:none;
}

tr {
  border-top: 1px solid #C1C3D1;
  border-bottom-: 1px solid #C1C3D1;
  color:#666B85;
  font-size:16px;
  font-weight:normal;
  text-shadow: 0 1px 1px rgba(256, 256, 256, 0.1);
}

tr:hover td {
  background:#4E5066;
  color:#FFFFFF;
  border-top: 1px solid #22262e;
}

tr:first-child {
  border-top:none;
}

tr:last-child {
  border-bottom:none;
}

tr:nth-child(odd) td {
  background:#EBEBEB;
}

tr:nth-child(odd):hover td {
  background:#4E5066;
}

tr:last-child td:first-child {
  border-bottom-left-radius:3px;
}

tr:last-child td:last-child {
  border-bottom-right-radius:3px;
}

td {
  background:#FFFFFF;
  padding:20px;
  text-align:left;
  vertical-align:middle;
  font-weight:300;
  font-size:18px;
  text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
  border-right: 1px solid #C1C3D1;
}

td:last-child {
  border-right: 0px;
}

th.text-left {
  text-align: left;
}

th.text-center {
  text-align: center;
}

th.text-right {
  text-align:  right;
}

td.text-left {
  text-align: left;
}

td.text-center {
  text-align: center;
}

td.text-right {
  text-align: right;
}



.fadein img {
    opacity:0;
    animation-name: fade;
    animation-duration: 6s;
    animation-iteration-count: infinite; 
    position:absolute;
    left:0;
    right:0;
    width:40%;
    float :left;
    height:90vh;
    overflow: hidden; 

}


.fadein img:nth-child(1) { animation-delay: 0s; }
.fadein img:nth-child(2) { animation-delay: 3s; }
/* .fadein img:nth-child(3) { animation-delay: 6s; } */



 @keyframes fade {
  0%   { opacity: 0; }
  11.11%   { opacity: 1; }
  33.33%  { opacity: 1; }
  44.44%  { opacity: 0; }
  100% { opacity: 0; }
} 
</style>

</head>

<body>

  <body>

  <section>
    <div class='container'>
      <div class='col-6'>
        <div class="fadein">

          <img  src="{{ product.image_1.url }}">
          <img  src="{{ product.image_2.url }}">
          <!-- <img style="height:194px width:259px" src="{{ product.image_3.url }}"> -->
            <!-- <img src="note4_2.jfif"><img src="note4_3.jfif"> -->
        </div>
      </div>
      <div class='col-6 description'>
       <div class="table-title">
<h3>{{ product.name }}</h3>
</div>
<table class="table-fill">
<thead>
<tr>
<th class="text-left">categories</th>
<th class="text-left">features</th>
</tr>
</thead>
<tbody class="table-hover">
<tr>
<td class="text-left">Product Category</td>
<td class="text-left">{{ product.category }}</td>
</tr>
<tr>
<td class="text-left">Product Name </td>
<td class="text-left">{{ product.name }}</td>
</tr>
<tr>
<td class="text-left">Description</td>
<td class="text-left">{{ product.description }}</td>
</tr>
<tr>
<td class="text-left">Product Price</td>
<td class="text-left">Rs. {{ product.price }}</td>
</tr>
<tr>
<td class="text-left">Product Availability</td>
<td class="text-left">{{ product.available }}</td>
</tr>
<tr>
<td class="text-left">Product Stock</td>
<td class="text-left">{{ product.stock }}</td>
</tr>
</tbody>
</table>
<br>
<button class='btn-primary'>
  <pre>
<form action="{% url "cart:cart_add" product.id %}" method="post">{% csrf_token %} {{ cart_product_form }}       <input type="submit" value="add to cart" ></form></button></pre>
      <!-- <button class='btn-primary'><a href="#">add to cart</a></button> -->
      </div>
    </div>
  </section>
</body>


</html>

shopmania/templates/shopmania/product/detail_old.html
{% extends 'shopmania/base.html' %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}

<h1 style="text-align: center; margin:10px; color: black; "> {{ product.name }} </h1>

<img src="{% if product.image_2 %} {{ product.image_2.url }} {% endif %}" alt="Product Image" style="height: 130px; width: auto">
<h3> Product Category :</h3> <p style="color: Blue"> {{ product.category }}   </p>
<h3> Product Name :</h3> <p style="color: Blue"> {{ product.name }}    </p>
<form action="{% url "cart:cart_add" product.id %}" method="post">
                               {% csrf_token %}
                               {{ cart_product_form }}
                               <input type="submit" value="add to cart" >
                           </form>
<h3> Product Description :</h3> <p style="color: Blue">  {{ product.description }}    </p>
<h3> Product Price :</h3> <p style="color: Blue">  Rs. {{ product.price }}    </p>
<h3> Product Availability :</h3> <p style="color: Blue">  {{ product.available}}   </p>
<h3> Product Stock :</h3> <p style="color: Blue">  {{ product.stock }}    </p>

{% endblock %}

shopmania/templates/shopmania/product/list.html
{% extends 'shopmania/base.html' %}
{% load static %}

{% block content %}

<!-- <h1 style="text-align: center; margin:10px; color: black; "> Products </h1> -->
<!--
{% for product in products %}

<a href="{{ product.get_absolute_url }}">
<img src="{% if product.image_2 %} {{ product.image_2.url }} {% endif %}" alt="Product Image" style="height: 130px; width: auto">
</a>

<h3>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
</h3>
<p>{{ product.price }}</p>

{% endfor %}

<h4>Categories</h4>
{% if not category %}
<ol>
  {% for c1 in categories %}
  <li>
    <a href="{{ c1.get_absolute_url }}">
      {{c1.name }}
    </a>
  </li>
  {% endfor %}
</ol>
{% endif %}

{% if category %}
{% for c in categories %}
<li {% if category.slug == c.slug %}{% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ol>
{% endif %} -->
{% endblock %}